### ISSUE TITLE
Add bot owner commands

### ISSUE THREAD

**Issue by danyspin97** [DanySpin97/PhpBotFramework#34]
Add commands that will be triggered only if the user is the bot owner.

**Comment by ghost** [comment]
Should they look like normal commands?

**Comment by danyspin97** [comment]
They can be created as a normal message command (first entity of type bot_command) but requires an additional array of telegram ids. If the user has the id contained in the array the command will be triggered.

**Comment by ghost** [comment]
What if the ID is not in the array:
Should we show an error or silently pass along?

**Comment by danyspin97** [comment]
If the ID is not contained in the array passed on command creation, don't trigger the command.
