### ISSUE TITLE
Make PhpBotFramework faster

### ISSUE THREAD

**Issue by ghost** [DanySpin97/PhpBotFramework#47]
I think the title can explain everything. Replace all " (the useless) in ', re-visit the function for http request and more, gotta go fast!

**Comment by danyspin97** [comment]
Please have a look [here](https://stackoverflow.com/questions/3446216/what-is-the-difference-between-single-quoted-and-double-quoted-strings-in-php) about the single/double quotes optimization.

And as far as I know the double quotes in PhpBotFramework are used only for exceptions.

What do you mean by "revisit the function for http request"?
For making requests PhpBotFramework uses [Guzzle](https://github.com/guzzle/guzzle) which is optimized and also run on machines without curl available.

The framework uses the GuzzleHTTP client which speed up all the requests of 300% after the first.
If you want to speed up PhpBotFramework please suggest or make a pull request.

**Comment by ghost** [comment]
Thank u for the answer. About the quotes, yes, I know what're the differences. 

About the HTTP Request, I rechecked the codes, and it's so fast, but it can be optimized.

Ah, remember, function in function are faster than a variable or key. 
(It's only a suggestion, I haven't rechecked for the function suggestion)
