### ISSUE TITLE
Return matches when MessageRegexCommand is used

### ISSUE THREAD

**Issue by ghost** [DanySpin97/PhpBotFramework#52]
Actually `MessageRegexCommand` only check if there's a matching but don't permits you to get the matches.

**Comment by ghost** [comment]
See my branch [regex-commad-args](https://github.com/tareph/PhpBotFramework/tree/regex-command-args) for an implementation proposal.

**Comment by ghost** [comment]
Seems good to me.
Ping @DanySpin97

**Comment by danyspin97** [comment]
How would you get the regex matches inside the closure that get called?

**Comment by ghost** [comment]
> How would you get the regex matches inside the closure that get called?

See [that commit](https://github.com/tareph/PhpBotFramework/commit/2ee0e9439d63424de32fb6efe54b22029fa504a4)
I've added a method `getArgsRegex` (inside the trait `CommandHandler`) that can be called from Bot class, so the closure can get the matches.

**Comment by ghost** [comment]
wow, thank you :D
